### ISSUE TITLE
Doesnt work with python 3.7

### ISSUE THREAD

**Issue by ayushin** [ambitioninc/django-regex-field#35]
```
  File "/Users/alexis/Work/Python/.virtualenvs/spareio/lib/python3.7/site-packages/regex_field/fields.py", line 96, in value_to_string
    if isinstance(obj, re._pattern_type):
AttributeError: module 're' has no attribute '_pattern_type'
```

**Comment by Lewellync** [comment]
It seems like this might be a more appropriate way to add Python 3.7 support:`try:
    Pattern = re._pattern_type
except AttributeError:
    # Python 3.7
    Pattern = re.Pattern`

**Comment by wesokes** [comment]
fixed in 2.0.0
