### PR TITLE
python 3.7 support (resolves #35)

### LINKED ISSUE #35: Doesnt work with python 3.7
```
  File "/Users/alexis/Work/Python/.virtualenvs/spareio/lib/python3.7/site-packages/regex_field/fields.py", line 96, in value_to_string
    if isinstance(obj, re._pattern_type):
AttributeError: module 're' has no attribute '_pattern_type'
```

### PR DESCRIPTION
**Pull request by rooterkyberian**
Python 3.7 support on travis is kinda wonky https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

Setting `dist: xenial, sudo: required` globally would break at very least python 3.4 tests. I guess it will be acceptable after 3.4 reaches EoL in 2019-03-16 (https://devguide.python.org/#branchstatus), but for now it seems better to keep that option to python 3.7 enough.

### CODE REVIEW

**Comment by wesokes** [comment]
added support up to python 3.8 and django 3.1 in version 0.7.0
